config/routes.rb
Rails.application.routes.draw do
  root to: 'gossips#index'
 resources :gossips
 resources :comments
 resources :cities
 resources :user
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
  has_many :gossips, through: :users
  validates :name,presence: true
  validates :zip_code,presence: true,uniqueness: true,
  format: { with: /\A(([0-8][0-9])|(9[0-5])|(2[ab]))[0-9]{3}\z/, message: "please enter a valid french zip code" }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
  validates :content,presence: true
  validates :user_id,presence: true
  validates :gossip_id,presence: true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :tag_gossip_links
  has_many :tags, through: :tag_gossip_links
  has_many :comments
  has_many :likes
  validates :title,presence: true,length: { in: 1..25 }
  validates :content,presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  has_many :recipient_to_pm_links, foreign_key: 'received_message_id'
  has_many :recipients, foreign_key: 'recipient_id', class_name: "User", through: :recipient_to_pm_links
end

app/models/recipient.rb
class Recipient < ApplicationRecord
  belongs_to :recipient, class_name: "User"
  belongs_to :received_message, class_name: "PrivateMessage"
end

app/models/tag.rb
class Tag < ApplicationRecord
 belongs_to :gossip
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :gossips
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :recipient_to_pm_links, foreign_key: 'recipient_id'
  has_many :received_messages, foreign_key: 'received_message_id', class_name: "PrivateMessage", through: :recipient_to_pm_links
  has_many :likes
  validates :email,presence: true,uniqueness: true,format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "Mauvais format" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  def index
    @gossip = Gossip.all
  end

  def show
    @find = Gossip.find(params[:id])
  end

  def new
    @gossip = Gossip.new
  end

  def create
    @gossip = Gossip.new(title: params[:title], content: params[:content], user_id: 4) # avec xxx qui sont les données obtenues à partir du formulaire

  if @gossip.save # essaie de sauvegarder en base @gossip
    redirect_to gossips_path
  else
    render new_gossip_path
  end
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    permitted_columns = params.require(:gossip).permit(:title, :content)
    @gossip.update_attributes(permitted_columns)

    redirect_to gossip_path
  end

  def destroy
    @gossip = Gossip.find(params[:id])
   @gossip.destroy

   redirect_to gossips_path
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
  end

  def show
    @users =  User.find(params[:id])
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/cities/create.html.erb
<h1>Cities#create</h1>
<p>Find me in app/views/cities/create.html.erb</p>

app/views/cities/destroy.html.erb
<h1>Cities#destroy</h1>
<p>Find me in app/views/cities/destroy.html.erb</p>

app/views/cities/edit.html.erb
<h1>Cities#edit</h1>
<p>Find me in app/views/cities/edit.html.erb</p>

app/views/cities/index.html.erb
<h1>Cities#index</h1>
<p>Find me in app/views/cities/index.html.erb</p>

app/views/cities/new.html.erb
<h1>Cities#new</h1>
<p>Find me in app/views/cities/new.html.erb</p>

app/views/cities/show.html.erb
<h1>Cities#show</h1>
<p>Find me in app/views/cities/show.html.erb</p>

app/views/cities/update.html.erb
<h1>Cities#update</h1>
<p>Find me in app/views/cities/update.html.erb</p>

app/views/gossips/create.html.erb
<h1>Gossips#create</h1>
<p>Find me in app/views/gossips/create.html.erb</p>

app/views/gossips/destroy.html.erb
<h1>Gossips#destroy</h1>
<p>Find me in app/views/gossips/destroy.html.erb</p>

app/views/gossips/edit.html.erb
<%= form_for @gossip do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/gossips/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Gossip</title>

  <!-- Bootstrap core CSS -->
  <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="css/grayscale.min.css" rel="stylesheet">

</head>

<body id="page-top">

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand js-scroll-trigger" href="#page-top">Accueil</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#about">About</a>
          </li>
          <li class="nav-item">
           <p class="nav-link js-scroll-trigger">  <%= link_to "creer un nouveau potin", new_gossip_path%> </p>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="/contact">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Header -->
  <header class="masthead">
    <div class="container d-flex h-100 align-items-center">
      <div class="mx-auto text-center">
        <h1 class="mx-auto my-0 text-uppercase">Bienvenue</h1>
        <h2 class="text-white-50 mx-auto mt-2 mb-5">Voici notre super site de potin.</h2>
        <a href="#potin" class="btn btn-primary js-scroll-trigger">Listes des potins</a>
      </div>
    </div>
  </header>

  <!-- About Section -->
  <section id="about" class="about-section text-center">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 mx-auto">
          <h2 class="text-white mb-4">créer le 07 aout 2019</h2>
          <p class="text-white-50">Project by Fina & Anto
            <a href="https://github.com/">the GitHub pages</a>. Project Gossip</p>
        </div>
      </div>
      
    </div>
  </section>

  
  
  <!-- Signup Section -->
  <section id="signup" class="signup-section">
    <div class="container">
      <div class="row">
        <div class="col-md-10 col-lg-8 mx-auto text-center">

          <i class="far fa-paper-plane fa-2x mb-2 text-white"></i>
          <h2 class="text-white mb-5">Abonnez-vous pour recevoir des mises à jour!</h2>

          <form class="form-inline d-flex">
            <input type="email" class="form-control flex-fill mr-0 mr-sm-2 mb-3 mb-sm-0" id="inputEmail" placeholder="Entrer votre e-mail ...">
            <button type="submit" class="btn btn-primary mx-auto">Envoyer</button>
          </form>

        </div>
      </div>
    </div>
  </section>

  <!-- Contact Section -->
  <section class="contact-section bg-black">
    <div class="container">

      <div class="row">

        <div class="col-md-4 mb-3 mb-md-0">
          <div class="card py-4 h-100">
            <div class="card-body text-center">
              <i class="fas fa-map-marked-alt text-primary mb-2"></i>
              <h4 class="text-uppercase m-0">Address</h4>
              <hr class="my-4">
              <div class="small text-black-50">Antananarivo, MADAGASCAR</div>
            </div>
          </div>
        </div>

        <div class="col-md-4 mb-3 mb-md-0">
          <div class="card py-4 h-100">
            <div class="card-body text-center">
              <i class="fas fa-envelope text-primary mb-2"></i>
              <h4 class="text-uppercase m-0">Email</h4>
              <hr class="my-4">
              <div class="small text-black-50">
                <a href="#">hello@yourdomain.com</a>
              </div>
            </div>
          </div>
        </div>

        <div class="col-md-4 mb-3 mb-md-0">
          <div class="card py-4 h-100">
            <div class="card-body text-center">
              <i class="fas fa-mobile-alt text-primary mb-2"></i>
              <h4 class="text-uppercase m-0">Phone</h4>
              <hr class="my-4">
              <div class="small text-black-50">+1 (261) 3xxxxxxxx</div>
            </div>
          </div>
        </div>
      </div>

      <div class="social d-flex justify-content-center">
        <a href="#" class="mx-2">
          <i class="fab fa-twitter"></i>
        </a>
        <a href="#" class="mx-2">
          <i class="fab fa-facebook-f"></i>
        </a>
        <a href="#" class="mx-2">
          <i class="fab fa-github"></i>
        </a>
      </div>

    </div>
  </section>

  <!-- Potin Section -->
  <section id="potin" class="potin-section text-center">
    <div class="card">
      <div class="card-body" style="background-color: #1098E5;">
      <h1 style="text-align: center;">BIENVENUE!</h1>
      <h2 style="text-align: center;"> Ici c'est notre super site de potins, il est chouette, non ?</h2>
      </div>
    </div>



  

    <div class="card">
      <div class="card-body">
        <h3> Voici la listes des Gossips: </h3>
      </div>
    </div>

   <%=  @gossip.each_with_index do |gossip, index|%>
   <div class="card text-center">
   <div class="card-header" style="background-color: #048CAB;">
    Potin N° <%=index + 1%>
   </div>
   <div class="card-body" style="background-color: #AAAEB0;">
    <h3 class="card-title"><%= gossip.user.first_name %></h3>
    <h2 class="card-text"><%= gossip.title %></h2>
    <p  class="btn btn-primary" style="background-color: #2B2F2F;"> <%= link_to "Afficher le potin", gossip_path(gossip.id)%> </p>
    <p  class="btn btn-primary" style="background-color: #2B2F2F;"> <%= link_to 'Edit', edit_gossip_path(gossip) %> </p>
    <p  class="btn btn-primary" style="background-color: #2B2F2F;"> <%= link_to 'Delete', 
             gossip_path(gossip), 
                         method: :delete, 
                         data: { confirm: 'Are you sure?' } %> 
   </div>
   <div class="card-footer text-muted" style="background-color: #4E5554;">
    crée le <%= gossip.created_at%>
   </div>
   </div>
   <h3> _ </h3>
   <% end %>
  </section>
      
  

  <!-- Bootstrap core JavaScript -->
  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Plugin JavaScript -->
  <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

  <!-- Custom scripts for this template -->
  <script src="js/grayscale.min.js"></script>


  <svg id='squiggle-svg' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' xmlns:ev='http://www.w3.org/2001/xml-events' viewBox='0 0 20 4'>
    <path fill='none' stroke='#18b8be' stroke-width='1' class='squiggle' d='M0,3.5 c 5,0,5,-3,10,-3 s 5,3,10,3 c 5,0,5,-3,10,-3 s 5,3,10,3'/>
  </svg>





</body>

</html>

app/views/gossips/new.html.erb
<form action= <%= gossips_path %> method="POST">
      <input type="hidden" name="authenticity_token" value=<%= form_authenticity_token %> >
      Title <input type="text" name="title"><br>
      Content <input type="text" name="content"><br>
      <input type="submit" value="Valider">
</form>

app/views/gossips/show.html.erb
<head>
  
</head>
<body>
  <div class="card text-center">
    <div class="card-header">
      <%= @find.user.first_name %> <%= @find.user.last_name %>
    </div>
    <div class="card-body">
     <h5 class="card-title"><%= @find.title %></h5>
      <p class="card-text"><%= @find.content %></p>
      <%= link_to "A  propos de l'auteur", user_path(@find.user.id)%>
    </div>
    <div class="card-footer text-muted">
      <%= @find.created_at %>
    </div>
  </div>
</body>

app/views/gossips/update.html.erb
<h1>Gossips#update</h1>
<p>Find me in app/views/gossips/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    
    <title>GossipProjectViews</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
  	
    <%= yield %>

  </body>
</html>

app/views/user/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

app/views/user/destroy.html.erb
<h1>User#destroy</h1>
<p>Find me in app/views/user/destroy.html.erb</p>

app/views/user/edit.html.erb
<h1>User#edit</h1>
<p>Find me in app/views/user/edit.html.erb</p>

app/views/user/index.html.erb
<h1>User#index</h1>
<p>Find me in app/views/user/index.html.erb</p>

app/views/user/new.html.erb
<h1>User#new</h1>
<p>Find me in app/views/user/new.html.erb</p>

app/views/user/show.html.erb
<head>
  
</head>
<body>
  <div class="card text-center">
      <div class="card-header">
        <h1> A propos de l'auteur</h1>
      </div>
  </div>

  <div class="alert alert-primary" role="alert">
   <h4> Nom : <%= @users.last_name %></h4>
  </div>
  <div class="alert alert-secondary" role="alert">
   <h4> Prénom : <%= @users.first_name %></h4>
  </div>
  <div class="alert alert-success" role="alert">
    <h4> Age : <%= @users.age %></h4>
  </div>
  <div class="alert alert-danger" role="alert">
    <h4> Description : <%= @users.description %></h4>
  </div>
  <div class="alert alert-warning" role="alert">
    <h4> Adresse mail : <%= @users.email %></h4>
  </div>
  <div class="alert alert-info" role="alert">
    <h4> Ville d'origine : <%= @users.city.name %></h4>
  </div>
</body>

app/views/user/update.html.erb
<h1>User#update</h1>
<p>Find me in app/views/user/update.html.erb</p>